### ISSUE TITLE
发送给打印机的数据太长，不能正确打印或打印不完整，要怎么处理？

### ISSUE THREAD

**Issue by lovelyelfpop** [liangminhua/cordova-posprinter-sample#10]
比如打印二维码，如果url太长，打印出来的二维码，扫描后得到的url末尾是乱码，比如
`https://order.keguanll.com/scan-order?orderId=169&twoDCId=19&authInfo=h_PFh-1V_rCzHUpYJqHvqmuCvf8%3D`
变成了
`https://order.keguanll.com/scan-order?orderId=169&twoDCId=19&auth�@�a� �(k�`

同样的，打印一个图片，数据太长，发过去打印不出来。

怎么拆分数据呢？

**Comment by liangminhua** [comment]
1.部分打印机支持打印二维码指令，未必要将二维码转换成图片。
2.由于打印机有固定的宽度规格，图片超长可以尝试旋转或者压缩。

**Comment by lovelyelfpop** [comment]
知道了 要用buffer.slice 分包，然后发送。蓝牙每次只能发一点

**Comment by B200019A** [comment]
我需要打印收据，可是我传送文字后，打印的数据不完整，少掉了几行。请问该如何解决。

**Comment by liangminhua** [comment]
自行实现文本分片逻辑。你可以咨询打印机厂商打印机的硬件规格，以调整代码适配具体的硬件。

________________________________
发件人: LaiJunJie ***@***.***>
发送时间: 2023年4月11日 15:04
收件人: liangminhua/cordova-posprinter-sample ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [liangminhua/cordova-posprinter-sample] 发送给打印机的数据太长，不能正确打印或打印不完整，要怎么处理？ (#10)


我需要打印收据，可是我传送文字后，打印的数据不完整，少掉了几行。请问该如何解决。
