### ISSUE TITLE
传送的数据过大，打印机会打印不完整的数据

### ISSUE THREAD

**Issue by B200019A** [liangminhua/cordova-posprinter-sample#11]

**Comment by B200019A** [comment]
var printText =
    EscCommand.InitializePrinter +
    EscCommand.TextAlignCenter +
    EscCommand.BoldOn +
    "Shop Name\n" +
    EscCommand.BoldOff +
    " No 22560, Jalan hahaha 19 , Bandar Putra , 81000 Kulai, Johor Malaysia\n" +
    "-------------------------------\n" +
    EscCommand.TextAlignLeft +
    `Date: ${new Date().toLocaleString()}\n` +
    "Receipt #: 1111\n" +
    "-------------------------------\n" +
    `Merchange Member: ${merchantMemberId}\n` +
    "-------------------------------\n" +
    `Item     Price   Qty   Amount\n` +
    EscCommand.TextAlignLeft +
    "-------------------------------\n" +
    `${products[0]}    2.00   2    ${subtotalPrice}\n` +
    "Product B  1.00   2    2.00\n" +
    "-------------------------------\n" +
    "Total Items   2\n" +
    "-------------------------------\n" +
    "Total Price:                6.00\n"+
    "-------------------------------\n" +
    "Amount Received            RM10\n"+
    "Change Return              RM6\n"+
    "-------------------------------\n" +
    EscCommand.TextAlignCenter +
    "Thank You, Visit Again\n"+
    EscCommand.TextAlignLeft +
    "-------------------------------\n" +
    EscCommand.TextAlignCenter +
    "Power By Shop Name\n"+
    EscCommand.PrintAndFeedMaxLine+
    cutAndFeedLine();

我使用的thermal printer只打印到"Change Return              RM6\n"+这行 剩下的就直接忽略 没有打印出来

**Comment by liangminhua** [comment]
根据打印机规格，实现字符串分片处理。发送多次打印指令。

**Comment by B200019A** [comment]
好的 发送多次打印指令有什么建议吗？ 使用什么方法？

**Comment by liangminhua** [comment]
分段发送指令，或者以`EscCommand.printAndFeedLine(0)`隔开一定行数文字
https://github.com/liangminhua/cordova-posprinter-sample/blob/4adf04e051a8ac97c4d8ced94d5a6c558d8c4720/www/js/commands.js#L17

**Comment by B200019A** [comment]
好的 谢谢你
