### ISSUE TITLE
For Ionic2/3

### ISSUE THREAD

**Issue by rakeshravipati** [liangminhua/cordova-posprinter-sample#2]
Hi liangminhua,

I need to print using Network Printer. Please help me, how to use this with Ionic2/3 app.

**Comment by liangminhua** [comment]
Using [cordova-plugin-chrome-apps-sockets-tcp](https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-sockets-tcp) (or other plugins) to send ESC/TSC command to printer,you can refer to [here](https://github.com/liangminhua/cordova-posprinter-sample/blob/master/www/js/controllers.js#L3).

hope this helps

**Comment by rakeshravipati** [comment]
Thanks @liangminhua. I will try this plugin.
