### ISSUE TITLE
Print Images and Barcode

### ISSUE THREAD

**Issue by ahmad6242** [liangminhua/cordova-posprinter-sample#3]
Hello,
Thanks for such a nice sample code. I really appreciate your work. 
I little bit help needed, as i am new into this.
I want to print images and bar-codes and i have no idea how to do this. can you please include some sample code for this also. 
I will be very Thankful to you.

**Comment by liangminhua** [comment]
you need to know about the ESC/TSC commands(printer commands), the relevant manuals can be obtained from your printer service provider or google.It has the specified commands for printing images and barcodes.  When printing images, the DPI and pixels of the printed image should conform to the specifications of the printer.
Unfortunately,I don't have a printer now，looking forward to your pull request.

**Comment by ahmad6242** [comment]
Hello,

**Comment by ahmad6242** [comment]
Hello,
Can you please tell me how am i suppose to use these POS commands given in the Attached file,
i will be very Grateful to you..
Thanks, 👍 
[ESC-POS Command set.docx](https://github.com/liangminhua/cordova-posprinter-sample/files/1920091/ESC-POS.Command.set.docx)

**Comment by liangminhua** [comment]
just encode the command to what your printer supported character set ，and send it to printer, and then printer will follow command .Do what you want to do.
[REF1](https://github.com/liangminhua/cordova-posprinter-sample/blob/master/www/js/commands.js)
[REF2](https://github.com/liangminhua/cordova-posprinter-sample/blob/77a94f26ce8eb1ecc9c56d487b2b9cf533957eec/www/js/controllers.js#L44)

**Comment by ahmad6242** [comment]
Yes thanks for the Reply 
https://github.com/liangminhua/cordova-posprinter-sample/blob/77a94f26ce8eb1ecc9c56d487b2b9cf533957eec/www/js/controllers.js#L11
is that suppose to the Line where i am going to tell the Encoding method for my Printer?

Really Appreciate your Help... :)
Thanks Brother.
 

*JUST FOUND OUT THAT 
CHARACTER SET
By default , V1's multibyte(fit east asia etc) is on and the default character set is
simple chinese.
command list and parameter listed below:
close multibyte(single byte fit for europe area)：0x1C 0x2E
open multibyte(fit for east asia) ：0x1C 0x26
Set Single byte character set：0x1B 0x74 [parameter]
Single byte character set parameter list:
[para] [character set] [area]
0 "CP437";
2 "CP850";
3 "CP860";
4 "CP863";
5 "CP865";
13 "CP857";
14 "CP737";
15 "CP928";
16 "Windows-1252";
17 "CP866";
18 "CP852";
19 "CP858";
21 "CP874";
33 "Windows-775";
34 "CP855";
36 "CP862";
37 "CP864";
254 "CP855";
Set multibyte character set：1C 43 [parameter]
multibyte character set parameter list:
[para] [character set]
0x00 || 0x48 "**GB18030**";       ****************
//0x01 || 0x49 "BIG5";
0x02 || 0x50 "KSC5601";
(byte) 0xff "utf-8";


and i can see you are using **GB18030** in your sample APP... 
I still cant understand How i am suppose to use the Image Printing commands from the Document... :(

![image](https://user-images.githubusercontent.com/12858657/38916958-4540c4ca-42fa-11e8-8a79-90b0b90a67af.png)

**Comment by liangminhua** [comment]
If you want to print a picture,  just use this command to transfer the binary data of the picture.
![image](https://user-images.githubusercontent.com/11595308/38966914-2af88a36-43b7-11e8-9745-9c5247128ff2.png)

**Comment by ahmad6242** [comment]
Brother I tried using that also, 
Is there anything i am doing wrong, Please have a look. 

![image](https://user-images.githubusercontent.com/12858657/38976013-f0db2048-43c0-11e8-8567-46074740b2a4.png)
![image](https://user-images.githubusercontent.com/12858657/38976029-04f3f1a4-43c1-11e8-9b3a-072c9148b10f.png)


I think the Plugin you are using for the Bluetooth connectivity does not support Image printing. :( 
I AM Just Stuck over this Image Printing over a week now.

**Comment by liangminhua** [comment]
The printer just support [raster bit image](https://en.wikipedia.org/wiki/Raster_graphics).And image encode to bytes ,not base64.

**Comment by liangminhua** [comment]
@ahmad6242 Please help me test the dev branch,I don't have POS printer. hope it work.

**Comment by ahmad6242** [comment]
Can i have your Skype please so we can discuss somethings... !
Here is mine
live:ahmad.raza.streamline

**Comment by ahmad6242** [comment]
Hey Man... 
I have Sent You request on Skype... 
**live:ben302010**
is that your ID right?
