### ISSUE TITLE
Ionic plugin

### ISSUE THREAD

**Issue by soesantos** [liangminhua/cordova-posprinter-sample#5]
Hello bro, do you have ionic plugin and app example also?
Thanks

**Comment by liangminhua** [comment]
This is a ionic sample.

**Comment by soesantos** [comment]
I mean app code like this
https://github.com/infoxicator/StarprnDemoIonicV2

**Comment by soesantos** [comment]
Ionic 3

**Comment by liangminhua** [comment]
The example to explain is irrelevant to the ionic version. Just know how to call the cordova plugin and you know how it works.I don‘t plan to upgrade the sample. #2 
Welcome pull request 😃
