### ISSUE TITLE
cordova, ionic, node version ?

### ISSUE THREAD

**Issue by munkh-altai** [liangminhua/cordova-posprinter-sample#6]
Hello
I am trying your on my mac.

But not working.  i got error msg. 
BUILD FAILED in 6s
(node:21482) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
bash-3.2$

**Comment by liangminhua** [comment]
Please use Cordova@6.3.0.
