### ISSUE TITLE
Is it possible to print QR Code? If so, how?

### ISSUE THREAD

**Issue by AldeirJampier** [liangminhua/cordova-posprinter-sample#8]

**Comment by liangminhua** [comment]
Some printers support QR codes printing commands. If printer not support QR code printing commands, you can print in picture mode. You can contact your equipment provider for development instruction documents.

**Comment by liangminhua** [comment]
you can easy to generate QR code command through [EscPosEncoder](https://github.com/NielsLeenheer/EscPosEncoder#qrcode).
