### ISSUE TITLE
como actualizarlo a ionic 4

### ISSUE THREAD

**Issue by jurara** [liangminhua/cordova-posprinter-sample#9]
he tratado de actualizarlo a la version 4 de ionic pero no he podido

**Comment by liangminhua** [comment]
Using cordova@6.3.1 can starup the project.

**Comment by jurara** [comment]
ya logre hacer que imprima tome tus archivos js e instale las librerias y ya se pudo imprimir

**Comment by uokivan** [comment]
@jurara
 me puedes enseñar, por favor
